<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="helloworld_tests.HelloWorldTest-20211219171610" tests="1" file="helloworld_tests.py" time="0.016" timestamp="2021-12-19T17:16:12" failures="0" errors="1" skipped="0">
	<testcase classname="helloworld_tests.HelloWorldTest" name="test_incorrect_login" time="0.016" timestamp="2021-12-19T17:16:12">
		<error type="AttributeError" message="'HelloWorldTest' object has no attribute 'client'"><![CDATA[Traceback (most recent call last):
  File "c:\users\hp\appdata\local\programs\python\python38\lib\unittest\case.py", line 60, in testPartExecutor
    yield
  File "c:\users\hp\appdata\local\programs\python\python38\lib\unittest\case.py", line 676, in run
    self._callTestMethod(testMethod)
  File "c:\users\hp\appdata\local\programs\python\python38\lib\unittest\case.py", line 633, in _callTestMethod
    method()
  File "c:\users\hp\desktop\builder\profiling\src\unittest\python\helloworld_tests.py", line 10, in test_incorrect_login
    with self.client:
AttributeError: 'HelloWorldTest' object has no attribute 'client'
]]></error>
	</testcase>
</testsuite>
